// ---------- Comfort+ ----------
cars.push_back(Car("Changan CS95","Changan", "Black", 4, 3.5, "Comfort+", 42800, false, 1, "", "YandexGo"));
cars.push_back(Car("Chery Arrizo 8","Chery", "Black", 4, 3.5, "Comfort+", 24600, false, 1, "", "YandexGo"));
cars.push_back(Car("Chery Tiggo 7 Plus","Chery", "Black", 4, 3.5, "Comfort+", 22400, false, 1, "", "YandexGo"));
cars.push_back(Car("Chery Tiggo 7 Pro","Chery", "Black", 4, 3.5, "Comfort+", 24600, false, 1, "", "YandexGo"));
cars.push_back(Car("Chery Tiggo 7 Pro Max","Chery", "Black", 4, 3.5, "Comfort+", 27800, false, 1, "", "YandexGo"));
cars.push_back(Car("Chery Tiggo 8","Chery", "Black", 4, 3.5, "Comfort+", 26800, false, 1, "", "YandexGo"));
cars.push_back(Car("Chery Tiggo 8 Pro","Chery", "Black", 4, 3.5, "Comfort+", 30400, false, 1, "", "YandexGo"));
cars.push_back(Car("Chery Tiggo 8 Pro Max","Chery", "Black", 4, 3.5, "Comfort+", 32600, false, 1, "", "YandexGo"));
cars.push_back(Car("Chery Tiggo 9","Chery", "Black", 4, 3.5, "Comfort+", 35800, false, 1, "", "YandexGo"));
cars.push_back(Car("Chrysler 300C","Chrysler", "Black", 4, 3.5, "Comfort+", 36800, false, 1, "", "YandexGo"));
cars.push_back(Car("Dongfeng Shine Max","Dongfeng", "Black", 4, 3.5, "Comfort+", 22600, false, 1, "", "YandexGo"));
cars.push_back(Car("EXEED LX","EXEED", "Black", 4, 3.5, "Comfort+", 39200, false, 1, "", "YandexGo"));
cars.push_back(Car("EXEED RX","EXEED", "Black", 4, 3.5, "Comfort+", 43200, false, 1, "", "YandexGo"));
cars.push_back(Car("EXEED TXL","EXEED", "Black", 4, 3.5, "Comfort+", 41200, false, 1, "", "YandexGo"));
cars.push_back(Car("EXEED VX","EXEED", "Black", 4, 3.5, "Comfort+", 45200, false, 1, "", "YandexGo"));
cars.push_back(Car("Ford Mondeo","Ford", "Black", 4, 3.5, "Comfort+", 29600, false, 1, "", "YandexGo"));
cars.push_back(Car("Geely Atlas","Geely", "Black", 4, 3.5, "Comfort+", 28600, false, 1, "", "YandexGo"));
cars.push_back(Car("Geely Atlas Pro","Geely", "Black", 4, 3.5, "Comfort+", 30400, false, 1, "", "YandexGo"));
cars.push_back(Car("Geely Monjaro","Geely", "Black", 4, 3.5, "Comfort+", 34800, false, 1, "", "YandexGo"));
cars.push_back(Car("Geely Preface","Geely", "Black", 4, 3.5, "Comfort+", 28600, false, 1, "", "YandexGo"));
cars.push_back(Car("Genesis G70","Genesis", "Black", 4, 3.5, "Comfort+", 40800, false, 1, "", "YandexGo"));
cars.push_back(Car("Genesis G80","Genesis", "Black", 4, 3.5, "Comfort+", 56800, false, 1, "", "YandexGo"));
cars.push_back(Car("Haval F7","Haval", "Black", 4, 3.5, "Comfort+", 26400, false, 1, "", "YandexGo"));
cars.push_back(Car("Hongqi E-QM5","Hongqi", "Black", 4, 3.5, "Comfort+", 32800, false, 1, "", "YandexGo"));
cars.push_back(Car("Hyundai Grandeur","Hyundai", "Black", 4, 3.5, "Comfort+", 42800, false, 1, "", "YandexGo"));
cars.push_back(Car("Hyundai Sonata","Hyundai", "Black", 4, 3.5, "Comfort+", 28800, false, 1, "", "YandexGo"));
cars.push_back(Car("Infiniti Q70","Infiniti", "Black", 4, 3.5, "Comfort+", 52800, false, 1, "", "YandexGo"));
cars.push_back(Car("Jaecoo J7","Jaecoo", "Black", 4, 3.5, "Comfort+", 28600, false, 1, "", "YandexGo"));
cars.push_back(Car("Jaguar XF","Jaguar", "Black", 4, 3.5, "Comfort+", 58800, false, 1, "", "YandexGo"));
cars.push_back(Car("Jetour Dashing","Jetour", "Black", 4, 3.5, "Comfort+", 22400, false, 1, "", "YandexGo"));
cars.push_back(Car("Jetour X90 PLUS","Jetour", "Black", 4, 3.5, "Comfort+", 26400, false, 1, "", "YandexGo"));
cars.push_back(Car("Kia Cadenza","Kia", "Black", 4, 3.5, "Comfort+", 38600, false, 1, "", "YandexGo"));
cars.push_back(Car("Kia K5","Kia", "Black", 4, 3.5, "Comfort+", 28600, false, 1, "", "YandexGo"));
cars.push_back(Car("Kia K7","Kia", "Black", 4, 3.5, "Comfort+", 42800, false, 1, "", "YandexGo"));
cars.push_back(Car("Kia K8","Kia", "Black", 4, 3.5, "Comfort+", 40800, false, 1, "", "YandexGo"));
cars.push_back(Car("Kia Optima","Kia", "Black", 4, 3.5, "Comfort+", 26800, false, 1, "", "YandexGo"));
cars.push_back(Car("Lexus ES","Lexus", "Black", 4, 3.5, "Comfort+", 45800, false, 1, "", "YandexGo"));
cars.push_back(Car("Lexus GS","Lexus", "Black", 4, 3.5, "Comfort+", 52800, false, 1, "", "YandexGo"));
cars.push_back(Car("Mazda 6","Mazda", "Black", 4, 3.5, "Comfort+", 29600, false, 1, "", "YandexGo"));
cars.push_back(Car("Toyota Avalon","Toyota", "Black", 4, 3.5, "Comfort+", 39800, false, 1, "", "YandexGo"));
cars.push_back(Car("Toyota Camry","Toyota", "Black", 4, 3.5, "Comfort+", 28800, false, 1, "", "YandexGo"));
cars.push_back(Car("Volkswagen Passat","Volkswagen", "Black", 4, 3.5, "Comfort+", 30400, false, 1, "", "YandexGo"));
cars.push_back(Car("Volvo S90","Volvo", "Black", 4, 3.5, "Comfort+", 59200, false, 1, "", "YandexGo"));
cars.push_back(Car("Voyah Dream","Voyah", "Black", 4, 3.5, "Comfort+", 45800, false, 1, "", "YandexGo"));
cars.push_back(Car("Voyah Passion","Voyah", "Black", 4, 3.5, "Comfort+", 42800, false, 1, "", "YandexGo"));
cars.push_back(Car("Zeekr 001","Zeekr", "Black", 4, 3.5, "Comfort+", 55800, false, 1, "", "YandexGo"));